name: dev workflow

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: main
  pull_request:
    branches: main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  test-ubuntu:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-versions: [3.7, 3.8, 3.9]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry tox tox-gh-actions

      - name: Install tesseract-ocr on Ubuntu
        run: sudo apt-get install -y tesseract-ocr

      - name: test with tox
        run:
          tox

      - name: list files
        run: ls -l .

      - uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
          files: coverage.xml
